#!/bin/bash

echo "📤 Sun Ocean 截图发送指南"
echo "=========================="
echo ""

# 检查文件是否存在
SCREENSHOT="$HOME/Desktop/sun-ocean-app-20260305-162949.png"
if [ ! -f "$SCREENSHOT" ]; then
    echo "❌ 截图文件不存在: $SCREENSHOT"
    echo "   请先运行: ./capture-browser.sh"
    exit 1
fi

echo "✅ 找到截图文件:"
echo "   文件: $(basename "$SCREENSHOT")"
echo "   大小: $(du -h "$SCREENSHOT" | cut -f1)"
echo "   尺寸: $(sips -g pixelWidth -g pixelHeight "$SCREENSHOT" 2>/dev/null | grep -E "pixelWidth|pixelHeight" | tr '\n' ' ')"
echo ""

echo "📱 发送方法:"
echo ""
echo "1. 🖱️  拖拽发送 (推荐)"
echo "   a. 打开飞书聊天窗口"
echo "   b. 打开Finder，进入桌面"
echo "   c. 拖拽此文件到飞书:"
echo "      $SCREENSHOT"
echo ""
echo "2. 📎 附件发送"
echo "   a. 飞书聊天窗口点击 📎 图标"
echo "   b. 选择'文件'"
echo "   c. 导航到桌面"
echo "   d. 选择: sun-ocean-app-20260305-162949.png"
echo ""
echo "3. 🖼️ 预览后发送"
echo "   a. 双击文件预览"
echo "   b. 预览窗口点击分享图标"
echo "   c. 选择飞书发送"
echo ""
echo "4. 💻 命令行辅助"
echo "   a. 打开文件: open \"$SCREENSHOT\""
echo "   b. 打开桌面: open ~/Desktop/"
echo "   c. 复制路径: echo \"$SCREENSHOT\" | pbcopy"
echo ""

echo "🔄 如果需要其他格式:"
echo ""
echo "# 转换为JPG (更小)"
echo "sips -s format jpeg \"$SCREENSHOT\" --out ~/Desktop/sun-ocean.jpg"
echo ""
echo "# 创建缩略图"
echo "sips -Z 800 \"$SCREENSHOT\" --out ~/Desktop/sun-ocean-small.jpg"
echo ""
echo "# 压缩PNG"
echo "pngquant --quality=65-80 \"$SCREENSHOT\" --output ~/Desktop/sun-ocean-compressed.png"
echo ""

echo "🔍 验证截图内容:"
echo ""
echo "截图显示:"
echo "• 🌊 Sun Ocean 应用标题"
echo "• 📋 '个人导航中心' 副标题"
echo "• 🎨 5个彩色分类卡片"
echo "• 🔗 每个卡片显示链接数量"
echo "• 🛠️ 底部操作按钮"
echo "• 🖥️ 浏览器窗口和桌面环境"
echo ""

echo "🚀 快速命令:"
echo "open \"$SCREENSHOT\"  # 打开截图"
echo "open ~/Desktop/      # 打开桌面"
echo ""

echo "📞 需要帮助?"
echo "1. 文件找不到? 运行: ./capture-browser.sh"
echo "2. 截图不清晰? 调整浏览器窗口后重试"
echo "3. 需要其他页面? 访问 http://localhost:3000 后截图"
echo ""

echo "🎉 现在请选择一种方法发送截图文件!"